version: "3"

services:
  datastore:
    image: windsockui/datastore
    ports:
        - "8080:8080"
    networks:
        - samplenet
    restart: always

  example:
    image: windsockui/example
    environment:
        DOMAIN : "localhost"
        DATABASE_URL : "http://datastore:8080"
    ports:
        - "3000:3000"
    depends_on:
      - datastore
    networks:
      - samplenet
    restart: always

networks:
  samplenet:
    driver: bridge